version: '3'

services:
  recentlyadded:
    image: ghcr.io/pukabyte/recentlyadded:latest
    container_name: recentlyadded
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - TZ=UTC 
    networks:
      - saltbox

networks:
  saltbox:
    external: true
