version: '3'

services:
  recently-added:
    build: .
    container_name: recently-added
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - TZ=UTC 
    networks:
      - saltbox

networks:
  saltbox:
    external: true
